services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./src/models/postgres_schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    
    volumes:
      - ./src/models/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js