CREATE TABLE bins (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name ~ '^[a-zA-Z0-9]{7}$')

);

CREATE TABLE requests (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bin_id int REFERENCES bins (id),
    time_stamp timestamp NOT NULL DEFAULT NOW(),
    http_method text
);
