CREATE TABLE bins (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name ~ '^[a-zA-Z0-9]{7}$')

);

CREATE TABLE requests (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bin_id int REFERENCES bins (id),
    time_stamp timestamp NOT NULL DEFAULT NOW(),
    mongodb_id text NOT NULL UNIQUE,
    http_method text
);

INSERT INTO bins (name) VALUES ('abcd123');
INSERT INTO requests (bin_id, mongodb_id, http_method)
VALUES (
    (SELECT id from bins WHERE name = 'abcd123'),
    '1234567890',
    'GET'
);

INSERT INTO requests (bin_id, mongodb_id, http_method)
VALUES (
    (SELECT id from bins WHERE name = 'abcd123'),
    '9876543210',
    'POST'
);