CREATE TABLE bins (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE

);

CREATE TABLE requests (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bin_id int REFERENCES bins (id) ON DELETE CASCADE,
    time_stamp timestamp NOT NULL DEFAULT NOW(),
    mongodb_id text NOT NULL UNIQUE,
    http_method text
);